language: java
sudo: false
install: true
dist: trusty
jdk:
- oraclejdk8
os:
- linux
branches:
  only:
  - develop
  - master
deploy:
  provider: heroku
  api_key:
    secure: nstKa8662Gw8DPOfmXsDnjF60WTXtVulssWYmlsig7JSfKvC4WFKDEr/xjio91h9nLF6voQGnLRhAy508iFsnFTWPqFMwHWb++o0GZo6fNAnaySL0x7JnP9qRg8EkOenwzenHjryrtsP6vky5DVBNOw7o/OCSrM6uqiM98H/kkL1ow8pvIAW4rwnjnMHe4UII+wnKLQpxz/K6USk9AuFJHO7NLoRwFpMtj3XT7Mstr52QLJlBqB3BZuzzC2LFvhDWNQKlxYPBFDiyRbtXagZ50NSzc9gvfu/SiY6wMdPLczBtNfPa1eormZ2kWsMNAmmYySQ33s2cZNPhn0FiJPDmtPN0vUw0Vg3Chw1YNPn0rrTPMg1QuyPR8jOxq599QFaEhQhPEx21AciuBqJtw2YqOH0+rJCYNZ0c1UNzoScwIDgRUrGN5sqtRMmx2DkFksJQvQYb794yhxPiHskVjC/20lbmfelWpx43enx2bjn2oAtbDmi/M9Ew9Fxg0o+p5WtaMlQN7Dj2U5AwKpbmwqfHjTvgAw0Nlt42y3SVEIdF19PVhRqGsoZhjnijZhXzGRZQt4EYxwRBx1oF6JoXls8VD5pJGYZMPjvE6gDnMBj/K95iVWw8cXDaBRg7s5YohdA+1HXPAmt8jhgrKEZnCzER9IKbiGIXJ9bLE3h9GwrPws=
  on:
    all_branches: true
  app: electronicqueue
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
addons:
  sonarcloud:
    organization: "$SONARCLOUD_ORGANIZATION"
    token:
      secure: "$SONARCLOUD_TOKEN"
script:
- "./gradlew assemble"
- "./gradlew check --rerun-tasks"
- sonar-scanner
- rm -rf .scannerwork
notifications:
  email:
    recipients:
    - oz-15@mail.ru
    - nekhoroshevmv@gmail.com
    - kashenkovsergej@yandex.ru
    - dantesakbars@mail.ru
    on_success: always
